config/routes.rb
  Rails.application.routes.draw do

  
  devise_for :users, :controllers => { :o_auth_callbacks => "users/o_auth_callbacks"}
  devise_scope  :users do 
    get 'users/sign_in', to: 'users/sessions#new', as: :new_session_path

    get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session_path
  end


  resources :users
  root "users#index"
end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2, :facebook]

  def self.from_google(email:, full_name:, uid:, avatar_url:)
    return nil unless email =~ /@mybusiness.com\z/
    create_with(uid: uid, full_name: full_name, avatar_url: avatar_url).find_or_create_by!(email: email)
  end

  def self.from_omniauth(auth)
  name_split = auth.info.name.split(" ")
  user = User.where(email: auth.info.email).first
  user ||= User.create!(provider: auth.provider, uid: auth.uid, last_name: name_split[0], first_name: name_split[1], email: auth.info.email, password: Devise.friendly_token[0, 20])
    user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def show 
  end

end

app/controllers/o_auth_callbacks_controller.rb
class Users::OAuthCallbackController < Devise::OAuthCallbackController	


	 def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

	def google_oauth2
    user = User.from_google(from_google_params)

    if user.present?
      sign_out_all_scopes
      flash[:success] = t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect user, event: :authentication
    else
      flash[:alert] = t 'devise.omniauth_callbacks.failure', kind: 'Google', reason: "#{auth.info.email} is not authorized."
      redirect_to new_session_path
    end
  end

  protected

  def after_omniauth_failure_path_for(_scope)
    new_session_path
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end

  private

  def from_google_params
    @from_google_params ||= {
      uid: auth.uid,
      email: auth.info.email,
      full_name: auth.info.name,
      avatar_url: auth.info.image
    }
  end

  def auth
    @auth ||= request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


	before_action :authenticate_user!

	def index
	end

	def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
    end

  	def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/o_auth_callback_helper.rb
module OAuthCallbackHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoginAuth</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Task-1</h1>
<p>Create Sign-in page.</p>

<h2>Products</h2>
<p>Order here please.</p>

<h3>Samsung A51</h3>

<%= button_to "Order Now", new_user_path %>


<% if current_user %>
<%= button_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
<%= button_to "Sign up", new_registration_path %>
<%= button_to "Sign In", new_session_path %>
<% end %>